# Generated by Django 5.2.9 on 2026-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_timezone_userpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_task_status_filter',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('all', 'All')], default='active', help_text="User's default filter for task status (active/completed/all)", max_length=20),
        ),
    ]
