# Generated by Django 5.2.9 on 2026-01-16 03:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0008_add_search_vector_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimePreferences',
            fields=[
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='time_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rounding_interval', models.IntegerField(choices=[(0, 'No rounding'), (5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes')], default=0, help_text='Time rounding interval in minutes (0 = no rounding)')),
                ('rounding_method', models.CharField(choices=[('up', 'Round up'), ('down', 'Round down'), ('nearest', 'Round to nearest')], default='nearest', help_text='Method for rounding time (up/down/nearest)', max_length=10)),
                ('idle_threshold_minutes', models.IntegerField(default=5, help_text='Minutes of inactivity before idle detection triggers')),
                ('pomodoro_work_minutes', models.IntegerField(default=25, help_text='Length of Pomodoro work interval in minutes')),
                ('pomodoro_break_minutes', models.IntegerField(default=5, help_text='Length of Pomodoro break interval in minutes')),
                ('default_billable_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default hourly billable rate', max_digits=10, null=True)),
                ('default_currency', models.CharField(default='USD', help_text='Default currency for billing (ISO 4217)', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When preferences were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When preferences were last updated')),
            ],
            options={
                'verbose_name': 'User Time Preferences',
                'verbose_name_plural': 'User Time Preferences',
                'db_table': 'user_time_preferences',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(help_text='Total duration of time entry (required)')),
                ('start_time', models.DateTimeField(blank=True, help_text='When timer was started (nullable for duration-only entries)', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When timer was stopped (nullable for running or duration-only entries)', null=True)),
                ('is_running', models.BooleanField(db_index=True, default=False, help_text='Whether timer is currently running')),
                ('description', models.TextField(blank=True, help_text='Additional notes or description for this time entry')),
                ('is_billable', models.BooleanField(db_index=True, default=False, help_text='Whether this time entry is billable')),
                ('billable_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for billing (nullable)', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency code for billing (ISO 4217)', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When time entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When time entry was last updated')),
                ('project', models.ForeignKey(blank=True, help_text='Project (TaskList) inherited from task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.tasklist')),
                ('task', models.ForeignKey(help_text='Task this time entry is linked to (required)', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who owns this time entry', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'db_table': 'time_entries',
                'ordering': ['-start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Sequential number of this Pomodoro session (1, 2, 3...)')),
                ('started_at', models.DateTimeField(help_text='When this Pomodoro session started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this Pomodoro session was completed', null=True)),
                ('was_completed', models.BooleanField(default=False, help_text='Whether this session was completed successfully')),
                ('break_taken', models.BooleanField(default=False, help_text='Whether user took a break after this session')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('time_entry', models.ForeignKey(help_text='Time entry this Pomodoro session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='time_tracking.timeentry')),
            ],
            options={
                'verbose_name': 'Pomodoro Session',
                'verbose_name_plural': 'Pomodoro Sessions',
                'db_table': 'pomodoro_sessions',
                'ordering': ['time_entry', 'session_number'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When tag was applied')),
                ('tag', models.ForeignKey(help_text='Tag applied to time entry', on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_tags', to='tasks.tag')),
                ('time_entry', models.ForeignKey(help_text='Time entry being tagged', on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_tags', to='time_tracking.timeentry')),
            ],
            options={
                'verbose_name': 'Time Entry Tag',
                'verbose_name_plural': 'Time Entry Tags',
                'db_table': 'time_entry_tags',
            },
        ),
        migrations.CreateModel(
            name='TimeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('total', 'Total')], help_text='Type of goal (daily/weekly/monthly/total)', max_length=10)),
                ('target_duration', models.DurationField(help_text='Target time duration for this goal')),
                ('start_date', models.DateField(blank=True, help_text='Start date for goal (optional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for goal (optional)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this goal is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When goal was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When goal was last updated')),
                ('project', models.ForeignKey(blank=True, help_text='Project this goal applies to (mutually exclusive with task)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_goals', to='tasks.tasklist')),
                ('task', models.ForeignKey(blank=True, help_text='Task this goal applies to (mutually exclusive with project)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_goals', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who set this goal', on_delete=django.db.models.deletion.CASCADE, related_name='time_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Goal',
                'verbose_name_plural': 'Time Goals',
                'db_table': 'time_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user'], name='time_entry_user_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task'], name='time_entry_task_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['project'], name='time_entry_project_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['start_time'], name='time_entry_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['is_running'], name='time_entry_is_running_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['is_billable'], name='time_entry_is_billable_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'start_time'], name='time_entry_user_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('start_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gt', datetime.timedelta(0))), name='positive_duration'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['time_entry'], name='pomodoro_time_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['started_at'], name='pomodoro_started_at_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pomodorosession',
            unique_together={('time_entry', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='timeentrytag',
            index=models.Index(fields=['time_entry'], name='time_entry_tag_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentrytag',
            index=models.Index(fields=['tag'], name='time_entry_tag_tag_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeentrytag',
            unique_together={('time_entry', 'tag')},
        ),
        migrations.AddIndex(
            model_name='timegoal',
            index=models.Index(fields=['user'], name='time_goal_user_idx'),
        ),
        migrations.AddIndex(
            model_name='timegoal',
            index=models.Index(fields=['project'], name='time_goal_project_idx'),
        ),
        migrations.AddIndex(
            model_name='timegoal',
            index=models.Index(fields=['task'], name='time_goal_task_idx'),
        ),
        migrations.AddIndex(
            model_name='timegoal',
            index=models.Index(fields=['goal_type'], name='time_goal_type_idx'),
        ),
        migrations.AddIndex(
            model_name='timegoal',
            index=models.Index(fields=['is_active'], name='time_goal_is_active_idx'),
        ),
    ]
