# Generated by Django 5.2.9 on 2026-01-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX time_entry_single_active_timer_idx
                ON time_entries (user_id)
                WHERE is_running = true;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS time_entry_single_active_timer_idx;
            """
        ),
    ]
