# Generated by Django 5.2.9 on 2026-01-16 03:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_search_vector_trigger'),
        ('time_tracking', '0002_add_single_active_timer_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeentry',
            name='positive_duration',
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', datetime.timedelta(0))), name='non_negative_duration'),
        ),
    ]
