# Generated by Django 5.2.9 on 2026-01-14 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userprofile_timezone_userpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title (required)', max_length=255)),
                ('priority', models.CharField(choices=[('P1', 'Urgent'), ('P2', 'High'), ('P3', 'Medium'), ('P4', 'Low')], help_text='Task priority level (P1=Urgent, P2=High, P3=Medium, P4=Low)', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', help_text='Current task status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Task description with markdown support')),
                ('due_date', models.DateField(blank=True, help_text='Date when task is due', null=True)),
                ('due_time', models.TimeField(blank=True, help_text='Specific time for deadline (requires due_date)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When task was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='task_workspace_status_idx'), models.Index(fields=['due_date'], name='task_due_date_idx'), models.Index(fields=['priority'], name='task_priority_idx'), models.Index(fields=['created_by'], name='task_created_by_idx'), models.Index(fields=['-created_at'], name='task_created_at_idx'), models.Index(fields=['workspace', 'created_by'], name='task_workspace_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__in', ['P1', 'P2', 'P3', 'P4'])), name='valid_priority'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed'])), name='valid_status')],
            },
        ),
    ]
