# Generated by Django 5.2.9 on 2026-01-14 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_timezone_userpreference_and_more'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='TaskList name (required)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='TaskList description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When task list was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When task list was last updated')),
            ],
            options={
                'verbose_name': 'Task List',
                'verbose_name_plural': 'Task Lists',
                'db_table': 'task_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_workspace_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_workspace_user_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(help_text='DEPRECATED: Use task_list.workspace instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_legacy', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this task list', on_delete=django.db.models.deletion.CASCADE, related_name='task_lists_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace this task list belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(help_text='Task list this task belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tasklist'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_list', 'status'], name='task_tasklist_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_list', 'created_by'], name='task_tasklist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['workspace'], name='tasklist_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['created_by'], name='tasklist_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['-created_at'], name='tasklist_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_tasklist_name_per_workspace'),
        ),
    ]
