# Generated by Django 5.2.9 on 2026-01-14 06:58

from django.db import migrations


def migrate_tasks_to_tasklists(apps, schema_editor):
    """
    Create a default task list for each workspace and migrate existing tasks.
    """
    Task = apps.get_model('tasks', 'Task')
    TaskList = apps.get_model('tasks', 'TaskList')
    Workspace = apps.get_model('accounts', 'Workspace')

    # Get all workspaces
    for workspace in Workspace.objects.all():
        # Create a default task list for this workspace
        default_list = TaskList.objects.create(
            name='My Tasks',
            description='Default task list',
            workspace=workspace,
            created_by=workspace.owner
        )

        # Migrate all tasks from this workspace to the default task list
        tasks = Task.objects.filter(workspace=workspace, task_list__isnull=True)
        for task in tasks:
            task.task_list = default_list
            task.save(update_fields=['task_list'])


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by clearing task_list references.
    """
    Task = apps.get_model('tasks', 'Task')
    Task.objects.all().update(task_list=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_tasklist_and_task_list_field'),
        ('accounts', '0001_initial'),  # Ensure Workspace model is available
    ]

    operations = [
        migrations.RunPython(migrate_tasks_to_tasklists, reverse_migration),
    ]
