# Generated by Django 5.2.9 on 2026-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_migrate_tasks_to_tasklists'),
    ]

    operations = [
        # Remove the old workspace field
        migrations.RemoveField(
            model_name='task',
            name='workspace',
        ),
        # Make task_list non-nullable
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(
                help_text='Task list this task belongs to',
                on_delete=models.deletion.CASCADE,
                related_name='tasks',
                to='tasks.tasklist'
            ),
        ),
    ]
