# Generated by Django 5.2.9 on 2026-01-14 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_timezone_userpreference_and_more'),
        ('tasks', '0004_finalize_tasklist_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (max 50 characters)', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for tag (e.g., #3B82F6)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When tag was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When tag was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this tag', on_delete=django.db.models.deletion.CASCADE, related_name='tags_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this tag belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this task', related_name='tasks', to='tasks.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['workspace'], name='tag_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['created_by'], name='tag_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tag_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_tag_name_per_workspace'),
        ),
    ]
