# Generated by Django 5.2.9 on 2026-01-15 09:23

from django.conf import settings
from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    """
    Backfill completed_at for existing completed tasks using updated_at value.
    This ensures existing completed tasks have a completion timestamp.
    """
    Task = apps.get_model('tasks', 'Task')

    # Update all completed tasks that don't have a completed_at timestamp
    completed_tasks = Task.objects.filter(
        status='completed',
        completed_at__isnull=True
    )

    # Backfill using updated_at as a reasonable approximation
    for task in completed_tasks:
        task.completed_at = task.updated_at
        task.save(update_fields=['completed_at'])


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration: clear completed_at for all tasks.
    This allows rolling back the migration cleanly.
    """
    Task = apps.get_model('tasks', 'Task')
    Task.objects.update(completed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_add_tag_model_and_tags_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When task was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether task is archived (soft delete)'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_list', 'status', 'is_archived'], name='task_list_status_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'active')), models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('completed_at__isnull', True), ('status', 'completed')), _connector='OR'), name='completed_at_requires_completed_status'),
        ),
        # Run data migration to backfill completed_at for existing completed tasks
        migrations.RunPython(backfill_completed_at, reverse_backfill),
    ]
