# Generated by Django 5.2.9 on 2026-01-15 12:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_completed_at_task_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=100)),
                ('query', models.TextField(help_text='Search query string')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filter configuration (workspace_id, tag_names, status, priority, date_range)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the search was saved')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the search was last updated')),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'saved_searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Search query string', max_length=255)),
                ('result_count', models.IntegerField(default=0, help_text='Number of results returned for this search')),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the search was performed')),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector for title and description', null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='task_search_vector_idx'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(help_text='User who saved this search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(help_text='User who performed the search', on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user'], name='saved_search_user_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', 'name'], name='saved_search_user_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_saved_search_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user'], name='search_history_user_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-searched_at'], name='search_history_user_date_idx'),
        ),
    ]
