# Generated by Django 5.2.9 on 2026-01-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_add_search_infrastructure'),
    ]

    operations = [
        # Create function to update search_vector for tasks
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION update_task_search_vector()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.search_vector :=
                    setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'B');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS update_task_search_vector() CASCADE;"
        ),

        # Create trigger to automatically update search_vector on task changes
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER task_search_vector_update
            BEFORE INSERT OR UPDATE OF title, description
            ON tasks
            FOR EACH ROW
            EXECUTE FUNCTION update_task_search_vector();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS task_search_vector_update ON tasks;"
        ),

        # Update existing tasks to populate search_vector
        migrations.RunSQL(
            sql="""
            UPDATE tasks
            SET search_vector =
                setweight(to_tsvector('english', COALESCE(title, '')), 'A') ||
                setweight(to_tsvector('english', COALESCE(description, '')), 'B');
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
